### ISSUE TITLE
Unable to add dependency

### ISSUE THREAD

**Issue by meisbokai** [Ubudu/Android-IndoorLocation-SDK#2]
Adding the following dependency in the build.gradle results in the following    

implementation ('com.ubudu.indoorlocation:ubudu-indoor-location-sdk:3.0.9@aar') {
        transitive = true
    }

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.ubudu.indoorlocation:ubudu-indoor-location-sdk:3.0.9.

**Comment by MGasztold** [comment]
Hello,

Please reach out to our customer success team. You need credentials to be able to fetch packages from our maven repository. I will add this information in the readme.
